config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  devise_for :users,
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root "products#index"

  namespace :admin do
    root "charts#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :suggested_products
    resources :csv, only: :create
    resources :charts, :line_chart
  end


  resources :orders
  resources :products do
    resources :comments
  end

  resources :suggested_products
  resources :categories, only: :show
  resources :favorite_products, only: [:create, :destroy]

  get "/cart", to: "cart#index"
  delete "/cart/:id/delete", to: "cart#destroy"
  post "/cart/:id", to: "cart#create"
  patch "/cart", to: "cart#update"
  get "/cart/:id/edit", to: "cart#edit"

  get "/:page", to: "static_pages#show"
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :validate!
  belongs_to :user
  has_many :order_details
  before_create :set_status_order, :set_bill_code
  delegate :name, to: :user, prefix: true
  enum status: [:processing, :delivering, :delivered, :cancelled]

  validates :shipping_address, presence: true

  scope :order_in_month, -> (start_date, end_date) do
    where("date(updated_at) > '#{start_date}' AND
      date(updated_at) <'#{end_date}'")
  end

  scope :order_count, -> date_time do
    where("date(created_at) = '#{date_time}'")
  end

  scope :sum_order, -> date_time do
    where("date(created_at) = '#{date_time}'")
  end

  def update_order! session_cart, address, phone
    product_carts = session_cart.map {|id, quantity|
      [Product.find_by(id: id), quantity]}
    self.update_attributes total_pay: calc_total_pay(product_carts),
      shipping_address: address,
      phone: phone
    if self.save
      session_cart.keys.each do |item|
        quantity = session_cart[item].to_i
        order_detail = self.order_details.build
        product_in_order = Product.find_by id: item.to_i
        rest_quantity = product_in_order.quantity - quantity
        product_in_order.update_attributes quantity: rest_quantity
        price = ApplicationController.helpers
          .calc_price_of_order_detail product_in_order, quantity
        order_detail.update quantity:  quantity,
          product_id: item.to_i,
          product_name: product_in_order.name,
          price: price
        order_detail.save
      end
      session_cart.clear
    end
  end

  def validate!
    errors.add(:shipping_address, :blank, message: "cannot be nil") if shipping_address.nil?
  end

  def self.to_xls(options = [])
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |order|
        csv << order.attributes.values_at(*column_names)
      end
    end
  end

  def calc_total_pay product_carts
    each_amount = []
    if product_carts
      product_carts.each do |product, quantity|
        each_amount << ApplicationController.helpers
          .calc_price_of_order_detail(product, quantity)
      end
    end
    total_pay = each_amount.inject(0) {|total_pay, price| total_pay += price}
  end

  private
  def set_status_order
    self[:status] = :processing
  end

  def set_bill_code
    self[:bill_code] = Settings.bill + Time.now.strftime(Settings.bill_date)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, :verify_admin
  layout "admin"

  def index
    @search = Order.search params[:q]
    @orders = @search.result.order(created_at: :DESC).page params[:page]
    respond_to do |format|
      format.html
      format.xls {send_data @orders.to_xls(col_sep: "\t")}
    end
  end

  def update
    unless params[:status].nil?
      if @order.update_attributes status: params[:status].to_i
        flash[:success] = t ".update_success"
      else
        flash[:notice] = t ".update_fail"
      end
      redirect_to admin_orders_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, :load_user
  before_action :load_session_cart, :load_order, only: [:new, :create]

  def index
    @orders = current_user.orders.order(created_at: :DESC).page params[:page]
  end

  def new
    @product_carts = @session_cart.map {|id, quantity|
      [Product.find_by(id: id), quantity]}
    @total_pay = @order.calc_total_pay @product_carts
  end

  def create
    if @order.update_order! @session_cart,
      params[:address], params[:phone]
      flash[:success] = t ".orders_create_successfully"
      OrderMailer.delay.confirm_order(@order, @user)
    else
      flash[:danger] = @order.errors.full_messages
    end
    redirect_to root_url
  end

  private
  def load_user
    @user = current_user
    render_404 unless @user
  end

  def load_order
    @order = @user.orders.build
  end
  def load_session_cart
    @session_cart = session[:cart]
    redirect_to root_url if @session_cart.blank?
  end
end

app/views/admin/orders/_form.html.erb
<%= form_tag admin_order_path(order) , method: :put do %>
  <div class="col-md-6">
    <%= select_tag :status, options_for_select(Order.statuses, params[:status]),
      class: "form-control" %>
  </div>
  <div class="col-md-4">
    <%= submit_tag t(".change"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/orders/index.html.erb
<div class="row">
  <h2 class="head"><%= t ".list_orders" %></h2>
    <div class="search-forms container">
      <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
        <div class="form-group">
          <%= f.label :bill_code_cont, t(".bill_code") %>
          <%= f.text_field :bill_code_cont, class: "form-control" %><br>
        </div>
        <div class="form-group">
          <%= f.label :total_pay_gteq, t(".greaterthan") %>
          <%= f.text_field :total_pay_gteq, class: "form-control" %><br>
        </div>
        <div class="form-group">
          <%= f.label :total_pay_lteq, t(".lessthan") %>
          <%= f.text_field :total_pay_lteq, class: "form-control" %><br>
        </div>
        <div class= "form-group" >
          <%= f.submit t(".search"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-10">
      <p>
        <%= t ".download" %>:
        <%= link_to t(".excel_By_Xml"), admin_orders_path(format: "xls") %>
      </p>
    </div>
  <table class="responstable">
    <thead>
      <tr class="info row">
        <th class="col-md-1"><%= t ".status" %></th>
        <th class="col-md-1"><%= t ".total_pay" %></th>
        <th class="col-md-2"><%= t ".shipping_address" %></th>
        <th class="col-md-2"><%= t ".phone" %></th>
        <th class="col-md-2"><%= t ".bill_code" %></th>
        <th class="col-md-4"><%= t ".update" %></th>
      </tr>
    </thead>
    <tbody>
      <% if @orders.any? %>
        <% @orders.each do |order|%>
          <tr class="row">
            <td class="col-md-1"><%= order.status %></td>
            <td class="col-md-1"><%= order.total_pay %></td>
            <td class="col-md-2"><%= order.shipping_address %></td>
            <td class="col-md-2"><%= order.phone %></td>
            <td class="col-md-2"><%= order.bill_code %></td>
            <td class="col-md-4">
              <%= render "form", order: order %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders%>
</div>