config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  devise_for :users,
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root "products#index"

  namespace :admin do
    root "charts#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :suggested_products
    resources :csv, only: :create
    resources :charts, :line_chart
  end


  resources :orders
  resources :products do
    resources :comments
  end

  resources :suggested_products
  resources :categories, only: :show
  resources :favorite_products, only: [:create, :destroy]

  get "/cart", to: "cart#index"
  delete "/cart/:id/delete", to: "cart#destroy"
  post "/cart/:id", to: "cart#create"
  patch "/cart", to: "cart#update"
  get "/cart/:id/edit", to: "cart#edit"

  get "/:page", to: "static_pages#show"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :suggested_products
  has_many :products
  validates :name, presence: true, uniqueness: true, allow_blank: false

  def update_category id
    last_right = get_last_right
    if id.empty?
      last_right.nil? ? self.update(lft: 1, rgt: 2, depth: 0)
        : self.update(lft: last_right + 1, rgt: last_right + 2, depth: 0)
    else
      parent_category = Category.find_by id: id
      Category.where("rgt >= ?", parent_category.rgt)
        .update_all("rgt = rgt + 2")
      Category.where("lft >= ?", parent_category.rgt)
        .update_all("lft = lft + 2")
      self.update(lft: parent_category.rgt, rgt: parent_category.rgt + 1,
        depth: parent_category.depth + 1)
    end
  end

  def delete_category
    Category.where("rgt >= ?", self.rgt)
      .update_all("rgt = rgt - 2")
    Category.where("lft >= ?", self.rgt)
      .update_all("lft = lft - 2")
  end

  def is_leaf?
    self.rgt == self.lft + 1
  end

  private
  def get_last_right
    Category.maximum(:rgt)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, :verify_admin
  before_action :load_category_tree, only: [:index, :create]
  layout "admin"

  def index
    @search = Category.search params[:q]
    @categories = @search.result.order(created_at: :DESC).page params[:page]
  end

  def create
    @category = Category.new category_params
    if @category.update_category params[:parent_id]
      flash[:success] = t ".create_category_success"
    else
      flash[:notice] = t ".create_category_fail"
    end
    redirect_to :back
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
    else
      flash[:notice] = t".update_fail"
    end
    redirect_to :back
  end

  def destroy
    if !@category.is_leaf?
      flash[:notice] = t ".must_be_leaf"
    elsif @category.products.any?
      flash[:notice] = t ".notice_message"
    elsif @category.destroy && @category.delete_category
      flash[:success] = t ".delete_success"
    else
      flash[:notice] = t ".delete_fail"
    end
    redirect_to :back
  end
  private
  def category_params
    params.permit :name, :description
  end

  def load_category_tree
    categories = Category.all
    @categories_tree = []
    category_tree categories
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def show
    @search = @category.products.search params[:q]
    @products = @search.result.page params[:page]
  end
end

app/views/admin/categories/_category.html.erb
<tr class="category-row">
  <td class="col-md-1"><%= index_for category_counter, @categories.current_page,
    Settings.category.per_page %></td>
  <td class="col-md-2"><%= category.name %></td>
  <td class="col-md-4"><%= category.description %></td>
  <td class="col-md-1">
    <%= link_to "", "#category-modal-#{category.id}", data: {toggle: "modal"},
      class: "btn btn-warning fa fa-pencil" %>
  </td>
  <td class="col-md-1">
    <%= link_to "", [:admin, category],
      method: :delete, data: {confirm: t(".message_confirm", name: category.name)},
      class: "btn btn-danger fa fa-trash" %></td>
  </td>
</tr>
<%= form_tag admin_category_path(category) , method: :put,
  id: "edit-category-form" do %>
  <div id="category-modal-<%= category.id %>" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="head"><%= t ".edit_category" %></h3>
        </div>
        <div class="modal-body">
          <form role="form">
          <%= hidden_field_tag "id", category.id %>
            <div>
              <label><%= t ".name" %></label>
              <%= text_field_tag :name, params[:name], value: category.name,
                class: "form-control" %>
            </div>
            <div>
              <label><%= t ".description" %></label>
              <%= text_field_tag :description, params[:description],
                value: category.description, class: "form-control" %>
            </div>
            <div class="modal-footer">
              <%= submit_tag t(".update"), class: "btn btn-primary btn-submit" %>
              <button type="submit" class="btn btn-danger"
                data-dismiss="modal">
                <%= t ".cancel" %>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/_parent_category.html.erb
<%= select_tag :parent_id, options_for_select(@categories_tree.collect {
  |cat| ["#{'-' * cat.depth} #{cat.name}", cat.id]}, params[:parent_id]),
  {class: "form-control", id: "parent_category", include_blank: t(".none")} %>

app/views/admin/categories/index.html.erb
<% provide :title, t(".all_categories") %>
<h1 class="head"><%= t ".all_categories" %></h1>
<div class="row">
  <div class="search-forms container">
    <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
      <div class="form-group">
        <%= f.label :name_or_description_cont, t(".name_or_description") %>
        <%= f.text_field :name_or_description_cont, class: "form-control" %>
      </div>
      <div class= "form-group" >
        <%= f.submit t(".search"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <%= link_to t(".add_category"), "#category-modal", data: {toggle: "modal"},
      class: "btn btn-primary btn-add-category" %>
  </div>
</div>
<div class="table-responsive table-condensed ">
  <table class="responstable" id="list_category" cellspacing="5px">
    <tr>
      <th><%= t ".number" %></th>
      <th><%= t ".name" %></th>
      <th><%= t ".description" %></th>
      <th><%= t ".edit" %></th>
      <th><%= t ".delete" %></th>
    </tr>
    <tbody>
      <%= render @categories%>
    </tbody>
  </table>
  <%= paginate @categories %>
</div>
<%= form_tag admin_categories_path , method: :post,
  id: "add-category-form" do %>
  <div id="category-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3><%= t".add_category" %></h3>
        </div>
        <div class="modal-body">
          <form role="form">
            <div>
              <label><%= t ".category_parent" %></label>
              <div>
                <%= render "parent_category" %>
              </div>
            </div>
            <div>
              <label><%= t ".name" %></label>
              <%= text_field_tag :name, params[:name], class: "form-control" %>
            </div>
            <div>
              <label><%= t ".description" %></label>
              <%= text_area_tag :description, params[:description],
                class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
          <%= submit_tag t(".add"), class: "btn btn-primary"%>
            <button type="submit" class="btn btn-danger"
              data-dismiss="modal">
              <%= t ".cancel" %>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>