config/routes.rb
Rails.application.routes.draw do
  post "/rate", to: "rater#create", as: "rate"
  devise_for :users,
    controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root "products#index"

  namespace :admin do
    root "charts#index"
    resources :categories
    resources :products
    resources :users
    resources :orders
    resources :suggested_products
    resources :csv, only: :create
    resources :charts, :line_chart
  end


  resources :orders
  resources :products do
    resources :comments
  end

  resources :suggested_products
  resources :categories, only: :show
  resources :favorite_products, only: [:create, :destroy]

  get "/cart", to: "cart#index"
  delete "/cart/:id/delete", to: "cart#destroy"
  post "/cart/:id", to: "cart#create"
  patch "/cart", to: "cart#update"
  get "/cart/:id/edit", to: "cart#edit"

  get "/:page", to: "static_pages#show"
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  acts_as_paranoid

  belongs_to :category
  has_many :specifications, dependent: :destroy, inverse_of: :product
  has_many :comments
  has_many :order_details

  ratyrate_rateable "quality"

  delegate :name, to: :category, prefix: true

  paginates_per Settings.product.per_page
  validates :name, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}
  validates :price, presence: true, numericality: true
  validates :quantity, presence: true, numericality: { only_integer: true }
  mount_uploader :image, ImageUploader
  accepts_nested_attributes_for :specifications, allow_destroy: true,
    reject_if: proc{|attributes| attributes["feature_value"].blank?}
  scope :in_category, -> category_id do
    where category_id: category_id if category_id.present?
  end

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  class << self
    def hot_trend
      date = Time.now - 5.day
      product_ids = "select order_details.product_id
       from order_details
       where (date(order_details.created_at) > '#{date}')
       group by order_details.product_id
       order by sum(order_details.quantity)"
     Product.where("id IN (#{product_ids})")
    end

    def import file
      CSV.foreach(file.path, headers: true, col_sep: "|",
        header_converters: :symbol) do |row|
        row = row.to_hash
        specifications_attributes = []
        row[:specifications].split(";").each do |spec|
          spec_hash = Hash.new
          arr_spec = spec.split(",")
          spec_hash[:feature_type] = arr_spec[0]
          spec_hash[:feature_value] = arr_spec[1]
          specifications_attributes.push spec_hash
        end
        row[:specifications_attributes] = specifications_attributes
        row.delete :specifications
        Product.create! row
      end
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, :load_all_leaf_categories
  layout "admin"

  def index
    @product = Product.new
    @search = Product.search params[:q]
    @products = @search.result.order(created_at: :DESC).page params[:page]
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".create_product_success"
    else
      flash[:notice] = t ".create_product_fail"
    end
    redirect_to :back
  end

  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t ".update_success"
    else
      flash[:notice] = t ".update_failed"
    end
    redirect_to :back
  end

  def destroy
    if @product.destroy
      flash[:success] = t ".deleted"
    else
      flash[:danger] = t ".fail_to_delete"
    end
    redirect_to :back
  end

  private

  def product_params
    params.require(:product).permit :category_id, :name, :description,
      :price, :image, :quantity,
      specifications_attributes: [:id, :feature_value, :feature_type, :_destroy]
  end

  def load_all_leaf_categories
    @categories_leaf = Category.all.reject {|category| !category.is_leaf?}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :load_session_recent_view

  def index
    @hot_trend_products = Product.hot_trend.limit(Settings.product.limit)
    @newest_products = Product.order(created_at: :desc)
      .limit(Settings.product.limit)
    @recent_products = session[:recent].map{|id| Product.find_by(id: id)} if
      session[:recent]
  end

  def show
    session[:recent] = [] unless session[:recent]
    if session[:recent].length >= Settings.max_recent
      session[:recent].delete_at 0
    end
    session[:recent].push @product.id
    @specifications = @product.specifications
    @comments = @product.comments.newest.page params[:page]
  end

  private
  def load_session_recent_view
    @cart = session[:recent] ? session[:recent] : []
  end
end

app/views/admin/products/_product.html.erb
<tr class="product-row">
  <td class="product_id col-sm-1">
    <%= index_for product_counter, @products.current_page,
      Settings.product.per_page %>
  </td>
  <td class="category_id col-sm-2"><%= product.category.name  %></td>
  <td class="product_name col-sm-2"><%= product.name %></td>
  <td class="product_name col-sm-2"><%= product.price %></td>
  <td class="product_name col-sm-1">
    <% if product.quantity == 0 %>
      <%= t".any_left"%>
    <% else %>
      <%= product.quantity %>
    <% end %>
  </td>
  <td class="product_name col-sm-2">
    <%= image_tag product.image? ?
      product.image.url : Settings.product_img, class: "img-responsive" %>
  </td>
  <td class="col-sm-1">
    <%= link_to "", "#product-modal-#{product.id}", data: {toggle: "modal"},
      class: "btn btn-warning fa fa-pencil" %>
  </td>
  <td class="col-sm-1">
    <%= link_to "", admin_product_path(product), method: :delete,
      data: {confirm: t(".confirm")}, class: "btn btn-danger fa fa-trash" %>
  </td>
</tr>
<%= form_for [:admin, product], url: admin_product_path(product) do |f| %>
  <div id="product-modal-<%= product.id %>" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5><%= t".edit_product" %></h5>
        </div>
        <form role="form row">
          <div class="modal-body row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :category %>
                <%= f.select :category_id, options_for_select(
                  @categories_leaf.collect{|cat|[cat.name, cat.id]},
                  {class: "form-control"}) %>
              </div>
              <div class="form-group">
                <%= f.label :name %>:
                <%= f.text_field :name, class: "form-control", required: true%>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :price %>:
                <%= f.text_field :price, class: "form-control", required: true%>
              </div>
              <div class="form-group">
                <%= f.label :quantity %>
                <%= f.text_field :quantity, class: "form-control", required: true %>
              </div>
              <div class="form-group">
                <%= f.label :image %>
                <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png",
                  multipart: true  %>
              </div>
            </div>
            <div class="form-group col-sm-12">
              <%= f.label :specifications %>:
              <%= f.fields_for :specifications do |builder| %>
                <%= render "specification_fields", f: builder %>
              <% end %>
            </div>
            <div class="col-sm-12">
              <div class="form-group">
                <label><%= t ".description" %></label>
                <%= f.text_area :description, class: "form-control", required: true%>
              </div>
            </div>
          </div>
          <div class="modal-footer">
          <%= f.submit t(".save"), class: "btn btn-primary add-product fa fa-plus"%>
            <button type="submit" class="btn btn-danger"
              data-dismiss="modal">
              <%= t ".cancel" %>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_specification_fields.html.erb
<div class="form-group specification_field col-sm-12">
  <div class="row">
    <div class="col-sm-4">
      <%= f.label :feature_type %>
      <%= f.text_field :feature_type, class: "form-control content-answer", required: true %>
    </div>
    <div class="col-sm-6">
      <%= f.label :feature_value %>
      <%= f.text_field :feature_value, class: "form-control content-answer", required: true %>
    </div>
    <div class="col-sm-2">
    <br>
      <%= link_to_remove_fields "", f %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <h3 class="text-center head"><%= t".list-product"%></h3>
  <div class="search-forms container">
    <%= search_form_for [:admin, @search], class: "form-inline" do |f| %>
      <div class="form-group">
        <%= f.label :name_or_description_cont, t(".name") %>
        <%= f.text_field :name_or_description_cont, class: "form-control" %><br>
      </div>
      <div class="form-group">
        <%= f.label :price_gteq, t(".greaterthan") %>
        <%= f.text_field :price_gteq, class: "form-control" %><br>
      </div>
      <div class="form-group">
        <%= f.label :price_lteq, t(".lessthan") %>
        <%= f.text_field :price_lteq, class: "form-control" %><br>
      </div>
      <div class= "form-group" >
        <%= f.submit t(".search"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-md-1">
    <%= link_to "", "#product-modal", data: {toggle: "modal"},
      class: "btn btn-primary btn-add-product fa fa-plus" %>
  </div>
  <div class="col-sm-1">
    <button type="button" class="btn btn-info" data-toggle="modal"
      data-target="#importModal"><%= t ".import" %></button>
    <div class="container">
      <div class="modal fade" id="importModal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">
                &times;</button>
              <h4 class="modal-title head"><%= t ".import_file" %></h4>
            </div>
            <div class="modal-body">
              <%= form_tag admin_csv_index_path, multipart: true do %>
                <%= file_field_tag :file %>
                <%= submit_tag t(".submit"), class: "btn btn-primary" %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger"
                data-dismiss="modal"><%= t ".close"%></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= form_for [:admin, @product], url: admin_products_path, method: :post do |f| %>
  <div id="product-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5><%= t".add_product" %></h5>
        </div>
        <form role="form row">
          <div class="modal-body row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :category %>
                <%= f.select :category_id, options_for_select(
                  @categories_leaf.collect{|cat|[cat.name, cat.id]},
                  {class: "form-control"}) %>
              </div>
              <div class="form-group">
                <%= f.label :name %>:
                <%= f.text_field :name, class: "form-control", required: true%>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= f.label :price %>:
                <%= f.text_field :price, class: "form-control", required: true%>
              </div>
              <div class="form-group">
                <%= f.label :quantity %>
                <%= f.text_field :quantity, class: "form-control", required: true %>
              </div>
              <div class="form-group">
                <%= f.label :image %>
                <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png",
                  multipart: true  %>
              </div>
            </div>
            <div class="form-group col-sm-12">
              <%= f.label :specifications %>:
              <%= f.fields_for :specifications do |builder| %>
                <%= render "specification_fields", f: builder %>
              <% end %>
            </div>
            <div class="form-group col-sm-12">
              <%= link_to_add_fields "", f, :specifications %>
            </div>
            <div class="col-sm-12">
              <div class="form-group">
                <label><%= t ".description" %></label>
                <%= f.text_area :description, class: "form-control", required: true%>
              </div>
            </div>
          </div>
          <div class="modal-footer">
          <%= f.submit t(".add"), class: "btn btn-primary add-product fa fa-plus"%>
            <button type="submit" class="btn btn-danger"
              data-dismiss="modal">
              <%= t ".cancel" %>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <% end %>
  <div class="table-responsive table-condensed col-sm-12">
    <table class="responstable" id="list_category">
      <tr>
        <th><%= t ".number" %></th>
        <th><%= t ".category" %></th>
        <th><%= t ".product_name" %></th>
        <th><%= t ".price" %></th>
        <th><%= t ".quantity" %></th>
        <th><%= t ".image" %></th>
        <th><%= t ".edit" %></th>
        <th><%= t ".delete" %></th>
      </tr>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>
    <%= paginate @products%>
  </div>
</div>